name: Analyze Tags
description: Get the current, previous and highest tag from git and outputs that for use in other actions
branding:
  icon: 'tag'
  color: 'gray-dark'
outputs:
  current_tag:
    description: The current tag
  highest_tag:
    description: The highest tag in the repository
runs:
  using: 'node12'
  main: 'dist/index.js'